// Generated by Dagger (https://dagger.dev).
package com.sysoliatina.jewelrystore.sharedPreferences;

import android.content.SharedPreferences;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import javax.inject.Provider;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class PrefsUtilsImpl_Factory implements Factory<PrefsUtilsImpl> {
  private final Provider<SharedPreferences> prefsProvider;

  public PrefsUtilsImpl_Factory(Provider<SharedPreferences> prefsProvider) {
    this.prefsProvider = prefsProvider;
  }

  @Override
  public PrefsUtilsImpl get() {
    return newInstance(prefsProvider.get());
  }

  public static PrefsUtilsImpl_Factory create(Provider<SharedPreferences> prefsProvider) {
    return new PrefsUtilsImpl_Factory(prefsProvider);
  }

  public static PrefsUtilsImpl newInstance(SharedPreferences prefs) {
    return new PrefsUtilsImpl(prefs);
  }
}
