// Generated by Dagger (https://dagger.dev).
package com.sysoliatina.jewelrystore.data.moderator;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import javax.inject.Provider;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class ModeratorDataSource_Factory implements Factory<ModeratorDataSource> {
  private final Provider<ModeratorService> commonServiceProvider;

  public ModeratorDataSource_Factory(Provider<ModeratorService> commonServiceProvider) {
    this.commonServiceProvider = commonServiceProvider;
  }

  @Override
  public ModeratorDataSource get() {
    return newInstance(commonServiceProvider.get());
  }

  public static ModeratorDataSource_Factory create(
      Provider<ModeratorService> commonServiceProvider) {
    return new ModeratorDataSource_Factory(commonServiceProvider);
  }

  public static ModeratorDataSource newInstance(ModeratorService commonService) {
    return new ModeratorDataSource(commonService);
  }
}
