// Generated by Dagger (https://dagger.dev).
package com.sysoliatina.jewelrystore.di;

import com.sysoliatina.jewelrystore.data.moderator.ModeratorService;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import javax.inject.Provider;
import retrofit2.Retrofit;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class AppModule_ProvideModeratorServiceFactory implements Factory<ModeratorService> {
  private final Provider<Retrofit> retrofitProvider;

  public AppModule_ProvideModeratorServiceFactory(Provider<Retrofit> retrofitProvider) {
    this.retrofitProvider = retrofitProvider;
  }

  @Override
  public ModeratorService get() {
    return provideModeratorService(retrofitProvider.get());
  }

  public static AppModule_ProvideModeratorServiceFactory create(
      Provider<Retrofit> retrofitProvider) {
    return new AppModule_ProvideModeratorServiceFactory(retrofitProvider);
  }

  public static ModeratorService provideModeratorService(Retrofit retrofit) {
    return Preconditions.checkNotNullFromProvides(AppModule.INSTANCE.provideModeratorService(retrofit));
  }
}
