// Generated by Dagger (https://dagger.dev).
package com.sysoliatina.jewelrystore.di;

import android.content.SharedPreferences;
import com.sysoliatina.jewelrystore.sharedPreferences.PrefsUtils;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import javax.inject.Provider;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class AppModule_ProvidePrefsUtilsFactory implements Factory<PrefsUtils> {
  private final Provider<SharedPreferences> sharedPreferencesProvider;

  public AppModule_ProvidePrefsUtilsFactory(Provider<SharedPreferences> sharedPreferencesProvider) {
    this.sharedPreferencesProvider = sharedPreferencesProvider;
  }

  @Override
  public PrefsUtils get() {
    return providePrefsUtils(sharedPreferencesProvider.get());
  }

  public static AppModule_ProvidePrefsUtilsFactory create(
      Provider<SharedPreferences> sharedPreferencesProvider) {
    return new AppModule_ProvidePrefsUtilsFactory(sharedPreferencesProvider);
  }

  public static PrefsUtils providePrefsUtils(SharedPreferences sharedPreferences) {
    return Preconditions.checkNotNullFromProvides(AppModule.INSTANCE.providePrefsUtils(sharedPreferences));
  }
}
