// Generated by Dagger (https://dagger.dev).
package com.sysoliatina.jewelrystore.di;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class AppModule_ProvidesBaseUrlFactory implements Factory<String> {
  @Override
  public String get() {
    return providesBaseUrl();
  }

  public static AppModule_ProvidesBaseUrlFactory create() {
    return InstanceHolder.INSTANCE;
  }

  public static String providesBaseUrl() {
    return Preconditions.checkNotNullFromProvides(AppModule.INSTANCE.providesBaseUrl());
  }

  private static final class InstanceHolder {
    private static final AppModule_ProvidesBaseUrlFactory INSTANCE = new AppModule_ProvidesBaseUrlFactory();
  }
}
