// Generated by Dagger (https://dagger.dev).
package com.sysoliatina.jewelrystore.di;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import okhttp3.logging.HttpLoggingInterceptor;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class AppModule_GetHttpLoggingInterceptorFactory implements Factory<HttpLoggingInterceptor> {
  @Override
  public HttpLoggingInterceptor get() {
    return getHttpLoggingInterceptor();
  }

  public static AppModule_GetHttpLoggingInterceptorFactory create() {
    return InstanceHolder.INSTANCE;
  }

  public static HttpLoggingInterceptor getHttpLoggingInterceptor() {
    return Preconditions.checkNotNullFromProvides(AppModule.INSTANCE.getHttpLoggingInterceptor());
  }

  private static final class InstanceHolder {
    private static final AppModule_GetHttpLoggingInterceptorFactory INSTANCE = new AppModule_GetHttpLoggingInterceptorFactory();
  }
}
