// Generated by Dagger (https://dagger.dev).
package com.sysoliatina.jewelrystore.di;

import android.content.Context;
import android.content.SharedPreferences;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import javax.inject.Provider;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class AppModule_ProvideEncryptedSharedPreferencesFactory implements Factory<SharedPreferences> {
  private final Provider<Context> contextProvider;

  public AppModule_ProvideEncryptedSharedPreferencesFactory(Provider<Context> contextProvider) {
    this.contextProvider = contextProvider;
  }

  @Override
  public SharedPreferences get() {
    return provideEncryptedSharedPreferences(contextProvider.get());
  }

  public static AppModule_ProvideEncryptedSharedPreferencesFactory create(
      Provider<Context> contextProvider) {
    return new AppModule_ProvideEncryptedSharedPreferencesFactory(contextProvider);
  }

  public static SharedPreferences provideEncryptedSharedPreferences(Context context) {
    return Preconditions.checkNotNullFromProvides(AppModule.INSTANCE.provideEncryptedSharedPreferences(context));
  }
}
