// Generated by Dagger (https://dagger.dev).
package com.sysoliatina.jewelrystore.di;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import javax.inject.Provider;
import okhttp3.OkHttpClient;
import retrofit2.Retrofit;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class AppModule_ProvideRetrofitFactory implements Factory<Retrofit> {
  private final Provider<String> bASE_URLProvider;

  private final Provider<OkHttpClient.Builder> httpBuilderProvider;

  public AppModule_ProvideRetrofitFactory(Provider<String> bASE_URLProvider,
      Provider<OkHttpClient.Builder> httpBuilderProvider) {
    this.bASE_URLProvider = bASE_URLProvider;
    this.httpBuilderProvider = httpBuilderProvider;
  }

  @Override
  public Retrofit get() {
    return provideRetrofit(bASE_URLProvider.get(), httpBuilderProvider.get());
  }

  public static AppModule_ProvideRetrofitFactory create(Provider<String> bASE_URLProvider,
      Provider<OkHttpClient.Builder> httpBuilderProvider) {
    return new AppModule_ProvideRetrofitFactory(bASE_URLProvider, httpBuilderProvider);
  }

  public static Retrofit provideRetrofit(String BASE_URL, OkHttpClient.Builder httpBuilder) {
    return Preconditions.checkNotNullFromProvides(AppModule.INSTANCE.provideRetrofit(BASE_URL, httpBuilder));
  }
}
