// Generated by Dagger (https://dagger.dev).
package com.sysoliatina.jewelrystore.di;

import com.sysoliatina.jewelrystore.data.client.ClientService;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import javax.inject.Provider;
import retrofit2.Retrofit;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class AppModule_ProvideClientServiceFactory implements Factory<ClientService> {
  private final Provider<Retrofit> retrofitProvider;

  public AppModule_ProvideClientServiceFactory(Provider<Retrofit> retrofitProvider) {
    this.retrofitProvider = retrofitProvider;
  }

  @Override
  public ClientService get() {
    return provideClientService(retrofitProvider.get());
  }

  public static AppModule_ProvideClientServiceFactory create(Provider<Retrofit> retrofitProvider) {
    return new AppModule_ProvideClientServiceFactory(retrofitProvider);
  }

  public static ClientService provideClientService(Retrofit retrofit) {
    return Preconditions.checkNotNullFromProvides(AppModule.INSTANCE.provideClientService(retrofit));
  }
}
