// Generated by Dagger (https://dagger.dev).
package com.sysoliatina.jewelrystore.di;

import com.sysoliatina.jewelrystore.data.common.CommonService;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import javax.inject.Provider;
import retrofit2.Retrofit;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class AppModule_ProvideCommonServiceFactory implements Factory<CommonService> {
  private final Provider<Retrofit> retrofitProvider;

  public AppModule_ProvideCommonServiceFactory(Provider<Retrofit> retrofitProvider) {
    this.retrofitProvider = retrofitProvider;
  }

  @Override
  public CommonService get() {
    return provideCommonService(retrofitProvider.get());
  }

  public static AppModule_ProvideCommonServiceFactory create(Provider<Retrofit> retrofitProvider) {
    return new AppModule_ProvideCommonServiceFactory(retrofitProvider);
  }

  public static CommonService provideCommonService(Retrofit retrofit) {
    return Preconditions.checkNotNullFromProvides(AppModule.INSTANCE.provideCommonService(retrofit));
  }
}
