// Generated by Dagger (https://dagger.dev).
package com.sysoliatina.jewelrystore.data.client;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import javax.inject.Provider;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class ClientRepository_Factory implements Factory<ClientRepository> {
  private final Provider<ClientDataSource> clientDataSourceProvider;

  public ClientRepository_Factory(Provider<ClientDataSource> clientDataSourceProvider) {
    this.clientDataSourceProvider = clientDataSourceProvider;
  }

  @Override
  public ClientRepository get() {
    return newInstance(clientDataSourceProvider.get());
  }

  public static ClientRepository_Factory create(
      Provider<ClientDataSource> clientDataSourceProvider) {
    return new ClientRepository_Factory(clientDataSourceProvider);
  }

  public static ClientRepository newInstance(ClientDataSource clientDataSource) {
    return new ClientRepository(clientDataSource);
  }
}
