// Generated by Dagger (https://dagger.dev).
package com.sysoliatina.jewelrystore.data.client;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import javax.inject.Provider;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class ClientDataSource_Factory implements Factory<ClientDataSource> {
  private final Provider<ClientService> clientServiceProvider;

  public ClientDataSource_Factory(Provider<ClientService> clientServiceProvider) {
    this.clientServiceProvider = clientServiceProvider;
  }

  @Override
  public ClientDataSource get() {
    return newInstance(clientServiceProvider.get());
  }

  public static ClientDataSource_Factory create(Provider<ClientService> clientServiceProvider) {
    return new ClientDataSource_Factory(clientServiceProvider);
  }

  public static ClientDataSource newInstance(ClientService clientService) {
    return new ClientDataSource(clientService);
  }
}
