// Generated by Dagger (https://dagger.dev).
package com.sysoliatina.jewelrystore.data.common;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import javax.inject.Provider;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class CommonRepository_Factory implements Factory<CommonRepository> {
  private final Provider<CommonDataSource> commonDataSourceProvider;

  public CommonRepository_Factory(Provider<CommonDataSource> commonDataSourceProvider) {
    this.commonDataSourceProvider = commonDataSourceProvider;
  }

  @Override
  public CommonRepository get() {
    return newInstance(commonDataSourceProvider.get());
  }

  public static CommonRepository_Factory create(
      Provider<CommonDataSource> commonDataSourceProvider) {
    return new CommonRepository_Factory(commonDataSourceProvider);
  }

  public static CommonRepository newInstance(CommonDataSource commonDataSource) {
    return new CommonRepository(commonDataSource);
  }
}
