// Generated by Dagger (https://dagger.dev).
package com.sysoliatina.jewelrystore.presentation.viewmodels;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class ClientProductsViewModel_HiltModules_KeyModule_ProvideFactory implements Factory<String> {
  @Override
  public String get() {
    return provide();
  }

  public static ClientProductsViewModel_HiltModules_KeyModule_ProvideFactory create() {
    return InstanceHolder.INSTANCE;
  }

  public static String provide() {
    return Preconditions.checkNotNullFromProvides(ClientProductsViewModel_HiltModules.KeyModule.provide());
  }

  private static final class InstanceHolder {
    private static final ClientProductsViewModel_HiltModules_KeyModule_ProvideFactory INSTANCE = new ClientProductsViewModel_HiltModules_KeyModule_ProvideFactory();
  }
}
