// Generated by Dagger (https://dagger.dev).
package com.sysoliatina.jewelrystore.presentation.viewmodels;

import com.sysoliatina.jewelrystore.data.client.ClientRepository;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import javax.inject.Provider;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class ClientProductsViewModel_Factory implements Factory<ClientProductsViewModel> {
  private final Provider<ClientRepository> clientRepositoryProvider;

  public ClientProductsViewModel_Factory(Provider<ClientRepository> clientRepositoryProvider) {
    this.clientRepositoryProvider = clientRepositoryProvider;
  }

  @Override
  public ClientProductsViewModel get() {
    return newInstance(clientRepositoryProvider.get());
  }

  public static ClientProductsViewModel_Factory create(
      Provider<ClientRepository> clientRepositoryProvider) {
    return new ClientProductsViewModel_Factory(clientRepositoryProvider);
  }

  public static ClientProductsViewModel newInstance(ClientRepository clientRepository) {
    return new ClientProductsViewModel(clientRepository);
  }
}
