// Generated by Dagger (https://dagger.dev).
package com.sysoliatina.jewelrystore.presentation.viewmodels;

import com.sysoliatina.jewelrystore.data.client.ClientRepository;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import javax.inject.Provider;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class ClientOrdersViewModel_Factory implements Factory<ClientOrdersViewModel> {
  private final Provider<ClientRepository> clientRepositoryProvider;

  public ClientOrdersViewModel_Factory(Provider<ClientRepository> clientRepositoryProvider) {
    this.clientRepositoryProvider = clientRepositoryProvider;
  }

  @Override
  public ClientOrdersViewModel get() {
    return newInstance(clientRepositoryProvider.get());
  }

  public static ClientOrdersViewModel_Factory create(
      Provider<ClientRepository> clientRepositoryProvider) {
    return new ClientOrdersViewModel_Factory(clientRepositoryProvider);
  }

  public static ClientOrdersViewModel newInstance(ClientRepository clientRepository) {
    return new ClientOrdersViewModel(clientRepository);
  }
}
