// Generated by Dagger (https://dagger.dev).
package com.sysoliatina.jewelrystore.presentation.viewmodels;

import com.sysoliatina.jewelrystore.data.common.CommonRepository;
import com.sysoliatina.jewelrystore.data.moderator.ModeratorRepository;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import javax.inject.Provider;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class ModeratorProductsViewModel_Factory implements Factory<ModeratorProductsViewModel> {
  private final Provider<ModeratorRepository> moderatorRepositoryProvider;

  private final Provider<CommonRepository> commonRepositoryProvider;

  public ModeratorProductsViewModel_Factory(
      Provider<ModeratorRepository> moderatorRepositoryProvider,
      Provider<CommonRepository> commonRepositoryProvider) {
    this.moderatorRepositoryProvider = moderatorRepositoryProvider;
    this.commonRepositoryProvider = commonRepositoryProvider;
  }

  @Override
  public ModeratorProductsViewModel get() {
    return newInstance(moderatorRepositoryProvider.get(), commonRepositoryProvider.get());
  }

  public static ModeratorProductsViewModel_Factory create(
      Provider<ModeratorRepository> moderatorRepositoryProvider,
      Provider<CommonRepository> commonRepositoryProvider) {
    return new ModeratorProductsViewModel_Factory(moderatorRepositoryProvider, commonRepositoryProvider);
  }

  public static ModeratorProductsViewModel newInstance(ModeratorRepository moderatorRepository,
      CommonRepository commonRepository) {
    return new ModeratorProductsViewModel(moderatorRepository, commonRepository);
  }
}
