// Generated by Dagger (https://dagger.dev).
package com.sysoliatina.jewelrystore.presentation.viewmodels;

import com.sysoliatina.jewelrystore.data.moderator.ModeratorRepository;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import javax.inject.Provider;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class ModeratorOrdersViewModel_Factory implements Factory<ModeratorOrdersViewModel> {
  private final Provider<ModeratorRepository> moderatorRepositoryProvider;

  public ModeratorOrdersViewModel_Factory(
      Provider<ModeratorRepository> moderatorRepositoryProvider) {
    this.moderatorRepositoryProvider = moderatorRepositoryProvider;
  }

  @Override
  public ModeratorOrdersViewModel get() {
    return newInstance(moderatorRepositoryProvider.get());
  }

  public static ModeratorOrdersViewModel_Factory create(
      Provider<ModeratorRepository> moderatorRepositoryProvider) {
    return new ModeratorOrdersViewModel_Factory(moderatorRepositoryProvider);
  }

  public static ModeratorOrdersViewModel newInstance(ModeratorRepository moderatorRepository) {
    return new ModeratorOrdersViewModel(moderatorRepository);
  }
}
