// Generated by Dagger (https://dagger.dev).
package com.sysoliatina.jewelrystore.presentation.viewmodels;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class ModeratorProductsViewModel_HiltModules_KeyModule_ProvideFactory implements Factory<String> {
  @Override
  public String get() {
    return provide();
  }

  public static ModeratorProductsViewModel_HiltModules_KeyModule_ProvideFactory create() {
    return InstanceHolder.INSTANCE;
  }

  public static String provide() {
    return Preconditions.checkNotNullFromProvides(ModeratorProductsViewModel_HiltModules.KeyModule.provide());
  }

  private static final class InstanceHolder {
    private static final ModeratorProductsViewModel_HiltModules_KeyModule_ProvideFactory INSTANCE = new ModeratorProductsViewModel_HiltModules_KeyModule_ProvideFactory();
  }
}
