// Generated by Dagger (https://dagger.dev).
package com.sysoliatina.jewelrystore.presentation.viewmodels;

import com.sysoliatina.jewelrystore.data.common.CommonRepository;
import com.sysoliatina.jewelrystore.sharedPreferences.PrefsUtils;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import javax.inject.Provider;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class SignUpViewModel_Factory implements Factory<SignUpViewModel> {
  private final Provider<CommonRepository> repositoryProvider;

  private final Provider<PrefsUtils> prefsUtilsProvider;

  public SignUpViewModel_Factory(Provider<CommonRepository> repositoryProvider,
      Provider<PrefsUtils> prefsUtilsProvider) {
    this.repositoryProvider = repositoryProvider;
    this.prefsUtilsProvider = prefsUtilsProvider;
  }

  @Override
  public SignUpViewModel get() {
    return newInstance(repositoryProvider.get(), prefsUtilsProvider.get());
  }

  public static SignUpViewModel_Factory create(Provider<CommonRepository> repositoryProvider,
      Provider<PrefsUtils> prefsUtilsProvider) {
    return new SignUpViewModel_Factory(repositoryProvider, prefsUtilsProvider);
  }

  public static SignUpViewModel newInstance(CommonRepository repository, PrefsUtils prefsUtils) {
    return new SignUpViewModel(repository, prefsUtils);
  }
}
