// Generated by Dagger (https://dagger.dev).
package com.sysoliatina.jewelrystore.presentation.viewmodels;

import com.sysoliatina.jewelrystore.data.client.ClientRepository;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import javax.inject.Provider;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class WishListViewModel_Factory implements Factory<WishListViewModel> {
  private final Provider<ClientRepository> clientRepositoryProvider;

  public WishListViewModel_Factory(Provider<ClientRepository> clientRepositoryProvider) {
    this.clientRepositoryProvider = clientRepositoryProvider;
  }

  @Override
  public WishListViewModel get() {
    return newInstance(clientRepositoryProvider.get());
  }

  public static WishListViewModel_Factory create(
      Provider<ClientRepository> clientRepositoryProvider) {
    return new WishListViewModel_Factory(clientRepositoryProvider);
  }

  public static WishListViewModel newInstance(ClientRepository clientRepository) {
    return new WishListViewModel(clientRepository);
  }
}
